version: "3"

services:
    namenode:
        image: apache/hadoop:3.3.6
        hostname: namenode
        command: ["hdfs", "namenode"]
        ports:
            - "9870:9870" # NameNode Web UI
            - "8020:8020" # HDFS RPC
        env_file: ./hadoop.env
        environment:
            - ENSURE_NAMENODE_DIR=/tmp/hadoop-hadoop/dfs/name
        volumes:
            - namenode_data:/tmp/hadoop-hadoop/dfs/name

    datanode:
        image: apache/hadoop:3.3.6
        hostname: datanode
        command: ["hdfs", "datanode"]
        env_file: ./hadoop.env
        depends_on:
            - namenode
        volumes:
            - datanode_data:/tmp/hadoop-hadoop/dfs/data

    resourcemanager:
        image: apache/hadoop:3.3.6
        hostname: resourcemanager
        command: ["yarn", "resourcemanager"]
        ports:
            - "8088:8088" # YARN Web UI
        env_file: ./hadoop.env
        depends_on:
            - namenode
            - datanode

    nodemanager:
        image: apache/hadoop:3.3.6
        hostname: nodemanager
        command: ["yarn", "nodemanager"]
        env_file: ./hadoop.env
        depends_on:
            - resourcemanager

    hive-server:
        image: apache/hive:3.1.3
        hostname: hive-server
        depends_on:
            - namenode
            - datanode
        environment:
            SERVICE_NAME: hiveserver2
            IS_RESUME: "true"
        ports:
            - "10000:10000" # HiveServer2 JDBC/Beeline
            - "10002:10002" # Hive Web UI

volumes:
    namenode_data:
    datanode_data:
